package com.HotPot.orm;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class Torder implements java.io.Serializable
{

	private String id;//订单ID
	private String bianhao;//订单编号
	private String shijian;//下单时间
	private String zhuangtai;//订单状态
	private int jine=0;//总金额
	private String user_id;//用户ID

	

	/** 默认构造函数 */
	public Torder()
	{
	}

	public String getBianhao()//得到订单编号
	{
		return bianhao;
	}

	public void setBianhao(String bianhao)//设置订单编号
	{
		this.bianhao = bianhao;
	}

	public String getId()//得到订单ID
	{
		return id;
	}

	public void setId(String id)//设置订单ID
	{
		this.id = id;
	}

	public int getJine()//得到总金额
	{
		return jine;
	}

	public void setJine(int jine)//设置总金额
	{
		this.jine = jine;
	}


	public String getShijian()//得到下单时间
	{
		return shijian;
	}

	public void setShijian(String shijian)//设置下单时间
	{
		this.shijian = shijian;
	}

	public String getUser_id()//得到用户ID
	{
		return user_id;
	}

	public void setUser_id(String user_id)//设置用户ID
	{
		this.user_id = user_id;
	}

	public String getZhuangtai()//得到订单状态
	{
		return zhuangtai;
	}

	public void setZhuangtai(String zhuangtai)//设置订单状态
	{
		this.zhuangtai = zhuangtai;
	}

	
}